/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.20")
    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib-jdk8"))
    implementation(kotlin("reflect"))
    
    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    
    
    // --- PoC Frameworks ---
    
    // - Server -
    implementation("io.javalin:javalin:2.7.0")
    implementation("org.slf4j:slf4j-simple:1.7.25")
    
    // - Dataz -
    implementation("com.beust:klaxon:5.0.5")
}

application {
    // Define the main class for the application.
    mainClassName = "kotlin_quick_monies.visual_interfaces.web.JavalinWebFrameworkWrapperKt"
}