/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm") version "1.3.20"
    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
    maven { setUrl("https://kotlin.bintray.com/kotlin-js-wrappers/") }
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib-jdk8"))
    implementation(kotlin("reflect"))
    
    // --- PoC Libs ---
    
    // - Server -
    implementation("io.javalin:javalin:2.7.0")
    implementation("org.slf4j:slf4j-simple:1.7.25")
    
    // - Ser-..client... serlcients. 
    implementation("com.squareup.retrofit2:retrofit:2.5.0")
    
    // - Data Serialization (because 'Dataz' was lame) -
//    implementation("com.beust:klaxon:5.0.5")
    
    implementation("com.squareup.moshi:moshi:1.8.0")
    implementation("com.squareup.moshi:moshi-kotlin:1.8.0")
    
    
    // - Time -
    implementation("joda-time:joda-time:2.10.1")
    
    // - Web Tools : CSS -
    implementation("org.jetbrains:kotlin-css-jvm:1.0.0-pre.69-kotlin-1.3.21")
}

application {
    // Define the main class for the application.
    mainClassName = "kotlin_quick_monies.visual_interfaces.web.JavalinWebFrameworkWrapperKt"
}
